name: CI

on:
  - push
  - pull_request

env:
  IMAGE_NAME: 42juododranoel/textflowrhyme-backend

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest

    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/actions/hello-world-docer-action:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Container
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{ env.TEST_TAG }}
          build-args: |
            TARGET=testing

      - name: Lint & Test
        run: |
          docker run --rm ${{ env.TEST_TAG }}     

      - name: Build & Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}
          build-args: |
            TARGET=deployment

  # build:
  #   name: Build
  #   if: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       platform:
  #         - "linux/amd64"  # "linux/arm/v7" "linux/arm64/v8" "linux/s390x" "linux/ppc64le"

  #   steps:
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v2.1.0

  #     - name: Cache Docker layers
  #       uses: actions/cache@v3
  #       with:
  #         path: /tmp/.buildx-cache
  #         key: ${{ runner.os }}-buildx-${{ matrix.platform }}-${{ github.sha }}
  #         restore-keys: ${{ runner.os }}-buildx-${{ matrix.platform }}-

  #     - name: Create a tag
  #       id: tag
  #       run: echo ::set-output "name=tag::$(echo ${{ matrix.platform }} | tr / -)"

  #     - name: Build
  #       uses: docker/build-push-action@v3.2.0
  #       with:
  #         push: false
  #         load: true
  #         tags: ${{ steps.tag.outputs.tag }}
  #         platforms: ${{ matrix.platform }}
  #         file: Dockerfile
  #         context: .
  #         cache-from: type=local,src=/tmp/.buildx-cache
  #         cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      # - name: Build Docker Image Archive
      #   id: archive
      #   env:
      #     TAG: ${{ steps.tag.outputs.tag }}
      #   run: |
      #     set -ex

      #     name=${TAG}.tar.gz
      #     docker save $TAG | gzip > $name
      #     echo ::set-output name=name::$name

      # - name: Upload Docker Image Archive
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: ${{ steps.archive.outputs.name }}
      #     path: ${{ steps.archive.outputs.name }}
      #     retention-days: 1

  # push:
  #   name: Push
  #   if: ${{ github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' && github.ref != 'refs/heads/template' }}
  #   needs: [ lint, test, build ]
  #   concurrency: docker
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Download Docker Image Archive
  #       uses: actions/download-artifact@v3

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v2.1.0
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.repository_owner }}
  #         password: ${{ secrets.github_token }}

  #     - name: Create and Push Tags
  #       run: |
  #         set -ex

  #         name=$IMAGE_NAME

  #         tag=${GITHUB_REF#refs/tags/v}
  #         branch=${GITHUB_REF#refs/heads/}

  #         if [[ $GITHUB_REF = refs/tags/v* ]]; then
  #           tags="v$tag latest"
  #         elif [[ $GITHUB_REF = refs/heads/* ]]; then
  #           tags="$branch"
  #         fi

  #         tags="$(echo $tags | tr / -)"
  #         echo Tags: $tags

  #         platforms=""
  #         for file in $(ls */*); do
  #           echo Loading $file
  #           platform=$(docker load -qi $file | cut -d' ' -f3)
  #           platform=${platform%:*}
  #           platforms="$platforms $platform"
  #           for tag in $tags; do
  #             tag=ghcr.io/$name:$tag-$platform
  #             docker tag $platform $tag
  #             docker push $tag
  #           done
  #         done

  #         for tag in $tags; do
  #           cmd="docker manifest create ghcr.io/$name:$tag"
  #           for platform in $platforms; do
  #             cmd="$cmd --amend ghcr.io/$name:$tag-$platform"
  #           done
  #           $cmd
  #           docker manifest push ghcr.io/$name:$tag
  #         done

  #     - name: Clear
  #       if: always()
  #       run: rm -f ${HOME}/.docker/config.json

# docker_deploy:
#   name: Docker Deploy
#   if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
#   needs: [ push ]
#   environment: server-test
#   runs-on: ubuntu-latest
#
#   steps:
#     - name: Deploy
#       env:
#         CREDENTIALS: ${{ secrets.UPDATE_CREDENTIALS }}
#         URL: ${{ secrets.UPDATE_URL }}
#       run: curl -u $CREDENTIALS $URL
